# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from trainer import robot_control_service_pb2 as trainer_dot_robot__control__service__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in trainer/robot_control_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotControlServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetObservation = channel.unary_unary(
                '/trainer.RobotControlService/GetObservation',
                request_serializer=trainer_dot_robot__control__service__pb2.GetObservationRequest.SerializeToString,
                response_deserializer=trainer_dot_robot__control__service__pb2.GetObservationResponse.FromString,
                _registered_method=True)
        self.TakeAction = channel.unary_unary(
                '/trainer.RobotControlService/TakeAction',
                request_serializer=trainer_dot_robot__control__service__pb2.TakeActionRequest.SerializeToString,
                response_deserializer=trainer_dot_robot__control__service__pb2.TakeActionResponse.FromString,
                _registered_method=True)
        self.GetGamepadAction = channel.unary_unary(
                '/trainer.RobotControlService/GetGamepadAction',
                request_serializer=trainer_dot_robot__control__service__pb2.GetGamepadActionRequest.SerializeToString,
                response_deserializer=trainer_dot_robot__control__service__pb2.TakeActionResponse.FromString,
                _registered_method=True)
        self.GetEpisodeControl = channel.unary_unary(
                '/trainer.RobotControlService/GetEpisodeControl',
                request_serializer=trainer_dot_robot__control__service__pb2.GetEpisodeControlRequest.SerializeToString,
                response_deserializer=trainer_dot_robot__control__service__pb2.GetEpisodeControlResponse.FromString,
                _registered_method=True)


class RobotControlServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetObservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TakeAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGamepadAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEpisodeControl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetObservation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObservation,
                    request_deserializer=trainer_dot_robot__control__service__pb2.GetObservationRequest.FromString,
                    response_serializer=trainer_dot_robot__control__service__pb2.GetObservationResponse.SerializeToString,
            ),
            'TakeAction': grpc.unary_unary_rpc_method_handler(
                    servicer.TakeAction,
                    request_deserializer=trainer_dot_robot__control__service__pb2.TakeActionRequest.FromString,
                    response_serializer=trainer_dot_robot__control__service__pb2.TakeActionResponse.SerializeToString,
            ),
            'GetGamepadAction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGamepadAction,
                    request_deserializer=trainer_dot_robot__control__service__pb2.GetGamepadActionRequest.FromString,
                    response_serializer=trainer_dot_robot__control__service__pb2.TakeActionResponse.SerializeToString,
            ),
            'GetEpisodeControl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEpisodeControl,
                    request_deserializer=trainer_dot_robot__control__service__pb2.GetEpisodeControlRequest.FromString,
                    response_serializer=trainer_dot_robot__control__service__pb2.GetEpisodeControlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trainer.RobotControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trainer.RobotControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotControlService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetObservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trainer.RobotControlService/GetObservation',
            trainer_dot_robot__control__service__pb2.GetObservationRequest.SerializeToString,
            trainer_dot_robot__control__service__pb2.GetObservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TakeAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trainer.RobotControlService/TakeAction',
            trainer_dot_robot__control__service__pb2.TakeActionRequest.SerializeToString,
            trainer_dot_robot__control__service__pb2.TakeActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGamepadAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trainer.RobotControlService/GetGamepadAction',
            trainer_dot_robot__control__service__pb2.GetGamepadActionRequest.SerializeToString,
            trainer_dot_robot__control__service__pb2.TakeActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEpisodeControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trainer.RobotControlService/GetEpisodeControl',
            trainer_dot_robot__control__service__pb2.GetEpisodeControlRequest.SerializeToString,
            trainer_dot_robot__control__service__pb2.GetEpisodeControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
